site_name: 'Motion'
site_description: 'An Open-Source Framework for Biomechanical Analysis'
site_author: 'Romain Martinez'
site_url: "https://romainmartinez.github.io/motion/"

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'teal'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
nav:
  - Getting Started: getting-started.md
  - User Guide:
    - Object creation: object-creation.md
    - Data processing: data-processing.md
  - Case Studies: case-studies.md
  - About: about.md
  - API reference:
      Analogs: api/analogs.md
      Angles: api/angles.md
      Markers: api/markers.md
      Dataarray_accessor: api/dataarray_accessor.md
      Rototrans: api/rototrans.md

markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      watch:
        - motion

repo_name: 'pyomeca/pyomeca'
repo_url: 'https://github.com/pyomeca/pyomeca'

copyright: 'Copyright &copy; 2019 Romain Martinez'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/romainmartinez'

extra_css:
  - custom.css
